import primszam

primszam.prims2(1)
print("\n")
print("1. teszteset")
print("Nem prímszám")
primszam.prims2(5)
print("\n")
print("2. teszteset")
print("Az 5 prímszám")
primszam.prims2(6)
print("\n")
print("3. teszteset")
print("Nem prímszám")
primszam.prims2(0)
print("\n")
print("4. teszteset")
print("Nem prímszám")
primszam.prims2(2)
print("\n")
print("5. teszteset")
print("A 2 prímszám")
primszam.prims2(-3)
print("\n")
print("6. teszteset")
print("Nem prímszám")
primszam.prims2(4)
print("\n")
print("7. teszteset")
print("Nem prímszám")
